services:
  - type: web
    name: douyin-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
